---
title: "Combine-climate-lite-scripts"
author: 
- name: Annie Kellner Dillon^[U.S.National Park Service, Climate Change Response Program, Fort Collins, CO]
-name: add additional authors as needed
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
abstract: This script combines all scripts previously run under CCRP's Climate Lite protocol for Resource Stewardship Strategies (RSS). 
---

```{r user-input}
# 12/12/2020 - Do not run parsing scripts. 
# Environments (.RData) that need to be loaded manually include 1) IntermediateFiles and 2) init_parsed
# Raw data that needs to be loaded is GridMet.csv

rm(list = ls())

SiteID = "CONG"
site <- "CONG"
state <- "South Carolina"

# The following needs to be inputted if the park centroid will not be used to select the MACA grid cell for the water balance model:

#MACA_lat <- 40.4465 
#MACA_lon <- -108.7651

```



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  collapse = TRUE,
  warning = TRUE, # set to FALSE when done
  message = TRUE, # set to FALSE when done
  fig.path = "figures/" # Alaska: NPS stores figures within parent directory of repo
)

library(here); library(plyr); # Use here::here when package lubridate is used
library(plotrix); library(zoo); library(ggplot2); library(grid); library(cowplot); library(reshape2); library(raster); library(ncdf4); library(reshape2); library(WriteXLS); library(data.table); library(RColorBrewer); library(ggrepel);library(plyr); library(lubridate); library(dplyr); library(forcats); library(openxlsx); library("WaterBalance"); library(sf); library(raster); library(rgdal);
library(tmap); library(tmaptools); library(rJava); library(OpenStreetMap); library(gridExtra); library(SPEI) 


# Enter the following code if you need to install Java and point R to the directory:
#Sys.setenv(JAVA_HOME='C:/Program Files/Java/jre1.8.0_261') # for 64-bit version #make sure to check the program file for the jre1 numbers.


```


## Historical Trends (PRISM)

```{r PRISM-parse, eval = FALSE, message=FALSE, warning=FALSE, echo=FALSE}

#source(here::here("./PRISM/RSS PRISM AN81 4km summarize v01.1.R")) # Parses PRISM data. Output = "PARK_lat_long_PRISM_PptTminTmax_IntermediateFiles.RData" # NOTE: Because this script is excluded, headers have not been changed

```

```{r PRISM-plots, results=hide, fig.path='./PRISM', eval=FALSE} 
# can add fig.path = './figures/PRISM when rewriting

source(here::here("PRISM", "RSS PRISM plots v1.2.R"),echo = FALSE)

```


## Climate Futures (MACA)

```{r Climate-Futures, echo=FALSE, fig.path='./figures/MACA', message=FALSE, warning=FALSE, results=HIDE}

# source(here::here("RSS_MACA_Parsing.R")) # Parse MACA data. Output = "_init_parsed.RData". Outputs to MACA folder.

# source(here::here("Gridmet-Parse.R")) # Parse GridMET data. Output = "GridMet.csv". Outputs to Gridmet folder.

source(here::here("scripts", "Climate-Futures", "RSS_MACA_Plot_Table_Creation.R"), local = knitr::knit_global()) # Requires "PARK_init_parsed.RData"; Output = "PARK_lat_long_Final_Environment.RData". 

source(here::here("scripts", "Climate-Futures", "RSS_MACA_Scatter and diagnostic.R"), local = knitr::knit_global()) # Creates scatter and diagnostic plots. Outputs to Figs MACA folder. 

source(here::here("scripts", "Climate-Futures", "RSS_Plotting_Bar_Charts.R")) # Requires "PARK_lat_long_Final_Environment.RData". Outputs plots and Excel Workbook to Figs MACA folder.

```

# Water Balance

```{r Water-Balance, message=FALSE, warning=FALSE, echo = FALSE, results=HIDE}

source(here::here("scripts", "WaterBalance", "get_params.R"))

source(here::here("scripts", "WaterBalance", "Daily_WB_batch_v2.R")) 
```

# Summary Plots

```{r Summary-Plots, message=FALSE, warning=FALSE, echo = FALSE, results=HIDE}
source(here::here("scripts", "SummaryPlots", "Summary plots.R"))

source(here::here("scripts", "SummaryPlots", "Summary WB plots.R")) 
```

# Additional Tables and Plots

```{r Additional-plots-and-tables, message= FALSE, warning=FALSE, echo=FALSE, results=HIDE}

source(here::here("scripts", "Additional-tables-plots", "RSS_MACA_drought_char.R"))

source(here::here("scripts", "Additional-tables-plots", "FLI FBI phenology plots.R"))

source(here::here("scripts", "Additional-tables-plots", "RSS Audubon summary.R"))
```

```{r}
sessionInfo() # Records package versions used
```

